# Compiler binary and flags
:compiler: 'nwnsc'
:flags: '-lowqey'

# Glob patterns matching nwscript to compile
:nss: ['src/*.nss', 'sm-utils/src/*.nss']

# Glob patterns matching yaml files to convert
:gff: ['src/*.*.yml']

# The default filename for the file to pack
:file: 'core_framework.erf'

# Demo module configuration. These settings overwrite the defaults.
:demo:
    :nss: 'demo/src/*.nss'
    :gff: 'demo/src/*.*.yml'
    :file: 'core_framework.mod'
